### ISSUE TITLE
As a community contributor, I don't want my content broken into multiple files

### ISSUE THREAD

**Issue by andymunro** [fbolton/nebel#2]
Is there any way to use Nebel to keep my content in larger files, not broken into smaller pieces that are harder to maintain.  If so, it would be easier for community contributors to keep contributing.

**Comment by pwright** [comment]
is this a nebel issue? or a mod-docs issue?

**Comment by andymunro** [comment]
Thanks, @pwright.  It's really a community issue with modular documentation, but it's no longer a concern for me.  Most SSO files are small anyway. If not, I will break them up, but leave the existing directory structure in place. Maintaining that directory structure eliminates disruption for the community.

**Comment by pwright** [comment]
@fbolton can be closed?

**Comment by fbolton** [comment]
@pwright Yes, closing.
