### ISSUE TITLE
README issue - fresh fedora installation doesn't work

### ISSUE THREAD

**Issue by pwright** [fbolton/nebel#6]
had to reinstall fedora, and when I run nebel I got:

<my path>/bin/nebel: line 6: python2: command not found

fixed by

sudo dnf install python2

ie it seems that python2 is not installed by default any more.

**Comment by gregraka** [comment]
Hi Paul,

I'm not a Fedora user, but a RHEL 8 user. I'll offer this up, as it might be similar to what's occurring on Fedora....

If I'm remembering correctly, on RHEL 8, both Python 2 and 3 are installed. I think the RHEL 8 folks didn't want to choose a default, so they left that up to each user. I created a symlink from **/usr/bin/python** to **/usr/bin/python2.7**.

Hope that is helpful,
--Greg

**Comment by pwright** [comment]
thanks @gregraka  I'm just reporting an issue with the readme, I was able to `sudo dnf install python2` as described and things ran fine

**Comment by pwright** [comment]
think we can close this one @fbolton ?
