### ISSUE TITLE
nebel on python3 branch 

### ISSUE THREAD

**Issue by pwright** [fbolton/nebel#9]
@fbolton  when I run `nebel` normally I get 

```
usage: nebel [-h] [-v]
             {assembly,procedure,concept,reference,create-from,split,book,mv,update}
             ...
nebel: error: too few arguments
```
However, running from python3 branch:
```
Traceback (most recent call last):
  File "<path>/nebel/bin/../nebel/commands.py", line 1794, in <module>
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```

However, some commands that I used worked fine, but I'm not sure if I'm running python3 or python2 when exercising these commands

**Comment by fbolton** [comment]
@pwright You are too quick for me! To get it to work on Python 2, I think you also need to install the wrapper package `six`, which smooths over the differences between Python 2 and Pythone 3. You can install it like this:
```
pip install six
```
Or maybe using sudo:
```
sudo pip install six
```
And then (hopefully!) the migrated Nebel will also work with Python 2. I am thinking of adding a WARNING + help message to the `nebel` script so that it automatically checks for the prerequisites and gives the user the necessary instructions for getting it to work again (e.g. installing the `six` package).

**Comment by roldanbob** [comment]
@fbolton I get very nearly the same error running on RHEL 8 w/ Python 3 active:

```
Traceback (most recent call last):
  File "<path>/nebel/bin/../nebel/commands.py", line 1878, in <module>
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```

I came looking here after receiving the following error while running nebel on this machine for the first time with the `fix-links` option:

```
Traceback (most recent call last):
  File "<path>/git/nebel/bin/../nebel/commands.py", line 1878, in <module>
    args.func(args)
  File "<path>/git/nebel/bin/../nebel/commands.py", line 787, in update
    self._update_fix_links(assemblyfiles, modulefiles, attrfilelist)
  File "<path>/git/nebel/bin/../nebel/commands.py", line 998, in _update_fix_links
    line = self._regexp_replace_link(line)
  File "<path>/git/nebel/bin/../nebel/commands.py", line 1030, in _regexp_replace_link
    new_value = regexp.sub(self._on_match_link, value)
  File "<path>/git/nebel/bin/../nebel/commands.py", line 1037, in _on_match_link
    new_anchorid = self._repair_anchorid(anchorid, self._on_match_fixfile)
  File "<path>/git/nebel/bin/../nebel/commands.py", line 1076, in _repair_anchorid
    for parent in self.parentassemblies[fixfile]:
KeyError: '<path>/assembly-<filename>.adoc'
```

Nebel processed a good many links before choking on that one file. Not sure how many files were not processed.

**Comment by roldanbob** [comment]
I should add that I was using Nebel from the `python3` branch.

**Comment by pwright** [comment]
closing, issue was caused by old module
